spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service
    username: seoin
    password: tjdls@2278
    driver-class-name: com.mysql.cj.jdbc.Driver

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: tjdls@1234